spring.application.name=banking-app
# ?? Server ????????????????????????????????????????????????????????????
server.port=8080

spring.jpa.properties.hibernate.discriminator.ignore_explicit_for_joined=true

# ?? H2 In-Memory Database ?????????????????????????????????????????????
spring.datasource.url=jdbc:h2:mem:bankingdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ?? JPA / Hibernate ???????????????????????????????????????????????????
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ?? H2 Browser Console ????????????????????????????????????????????????
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ?? JWT ???????????????????????????????????????????????????????????????
jwt.secret=3f8a2b1c9d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0
jwt.expiration-ms=86400000

# ?? CORS ??????????????????????????????????????????????????????????????
cors.allowed-origins=http://localhost:5173